// <auto-generated />
using System;
using Arcade.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Arcade.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251207193111_UpdateOrderSchema_AddEmailPhonePayment_RemoveStatePostalCountryNotes")]
    partial class UpdateOrderSchema_AddEmailPhonePayment_RemoveStatePostalCountryNotes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Arcade.Models.CartItem", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartItemId"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CartItemId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Arcade.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("IconClass")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Laptop",
                            Description = "Gaming & Professional Laptops",
                            DisplayOrder = 1,
                            IconClass = "fas fa-laptop",
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Monitor",
                            Description = "Gaming & Professional Monitors",
                            DisplayOrder = 2,
                            IconClass = "fas fa-desktop",
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "RAM",
                            Description = "DDR4 & DDR5 Memory Modules",
                            DisplayOrder = 3,
                            IconClass = "fas fa-memory",
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "SSD",
                            Description = "NVMe & SATA Solid State Drives",
                            DisplayOrder = 4,
                            IconClass = "fas fa-hdd",
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Mouse",
                            Description = "Gaming & Productivity Mice",
                            DisplayOrder = 5,
                            IconClass = "fas fa-mouse",
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Keyboard",
                            Description = "Mechanical & Membrane Keyboards",
                            DisplayOrder = 6,
                            IconClass = "fas fa-keyboard",
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "CPU",
                            Description = "Desktop Processors",
                            DisplayOrder = 7,
                            IconClass = "fas fa-microchip",
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "GPU",
                            Description = "Graphics Cards",
                            DisplayOrder = 8,
                            IconClass = "fas fa-tv",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("Arcade.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DeliveredDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("ShippedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Arcade.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ProductName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("Arcade.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SKU")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Brand = "ASUS",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "ASUS ROG Strix G15 Gaming Laptop with AMD Ryzen 9 7945HX, NVIDIA RTX 4070 8GB, 16GB DDR5 RAM, 1TB NVMe SSD, 15.6\" QHD 165Hz Display. Perfect for competitive gaming and content creation.",
                            ImageUrl = "https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=600&h=400&fit=crop",
                            IsActive = true,
                            IsFeatured = true,
                            Price = 69999.00m,
                            ProductName = "ASUS ROG Strix G15",
                            SKU = "ASUS-ROG-G15",
                            ShortDescription = "Ryzen 9, RTX 4070, 16GB RAM",
                            StockQuantity = 15
                        },
                        new
                        {
                            ProductId = 2,
                            Brand = "MSI",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "MSI Katana 15 Gaming Laptop with Intel Core i7-13620H, NVIDIA RTX 4060 8GB, 16GB DDR5 RAM, 512GB NVMe SSD, 15.6\" FHD 144Hz Display. Excellent value for gaming enthusiasts.",
                            ImageUrl = "https://images.unsplash.com/photo-1593642702821-c8da6771f0c6?w=600&h=400&fit=crop",
                            IsActive = true,
                            IsFeatured = true,
                            Price = 45999.00m,
                            ProductName = "MSI Katana 15",
                            SKU = "MSI-KATANA-15",
                            ShortDescription = "Intel i7, RTX 4060, 16GB RAM",
                            StockQuantity = 20
                        },
                        new
                        {
                            ProductId = 3,
                            Brand = "Lenovo",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lenovo Legion Pro 5 Gaming Laptop with AMD Ryzen 7 7745HX, NVIDIA RTX 4070 8GB, 32GB DDR5 RAM, 1TB NVMe SSD, 16\" WQXGA 165Hz Display. Premium build quality with excellent cooling.",
                            ImageUrl = "https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=600&h=400&fit=crop",
                            IsActive = true,
                            IsFeatured = true,
                            Price = 74999.00m,
                            ProductName = "Lenovo Legion Pro 5",
                            SKU = "LENOVO-LEGION-PRO5",
                            ShortDescription = "Ryzen 7, RTX 4070, 32GB RAM",
                            StockQuantity = 12
                        },
                        new
                        {
                            ProductId = 4,
                            Brand = "Dell",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Dell G15 5530 Gaming Laptop with Intel Core i5-13450HX, NVIDIA RTX 4050 6GB, 8GB DDR5 RAM, 512GB NVMe SSD, 15.6\" FHD 120Hz Display. Budget-friendly gaming laptop.",
                            ImageUrl = "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=600&h=400&fit=crop",
                            IsActive = true,
                            IsFeatured = false,
                            Price = 32999.00m,
                            ProductName = "Dell G15 5530",
                            SKU = "DELL-G15-5530",
                            ShortDescription = "Intel i5, RTX 4050, 8GB RAM",
                            StockQuantity = 25
                        },
                        new
                        {
                            ProductId = 5,
                            Brand = "Samsung",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Samsung Odyssey G7 32-inch Curved Gaming Monitor with QHD 2560x1440 resolution, 240Hz refresh rate, 1ms response time, HDR600, G-Sync Compatible. 1000R curvature for immersive gaming.",
                            ImageUrl = "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=600&h=400&fit=crop",
                            IsActive = true,
                            IsFeatured = true,
                            Price = 21999.00m,
                            ProductName = "Samsung Odyssey G7 32\"",
                            SKU = "SAMSUNG-G7-32",
                            ShortDescription = "QHD 240Hz Curved Gaming Monitor",
                            StockQuantity = 18
                        },
                        new
                        {
                            ProductId = 6,
                            Brand = "LG",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "LG UltraGear 27GP850 27-inch Gaming Monitor with Nano IPS technology, QHD 2560x1440 resolution, 165Hz refresh rate, 1ms response time, HDR400, G-Sync Compatible. Vibrant colors and fast response.",
                            ImageUrl = "https://images.unsplash.com/photo-1616711220408-a5e88d4cf0ad?w=600&h=400&fit=crop",
                            IsActive = true,
                            IsFeatured = true,
                            Price = 14999.00m,
                            ProductName = "LG UltraGear 27GP850",
                            SKU = "LG-27GP850",
                            ShortDescription = "QHD 165Hz Nano IPS",
                            StockQuantity = 22
                        },
                        new
                        {
                            ProductId = 7,
                            Brand = "ASUS",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "ASUS TUF Gaming VG279QM 27-inch Monitor with Fast IPS panel, FHD 1920x1080 resolution, 280Hz overclocked refresh rate, 1ms response time, G-Sync Compatible. ELMB Sync technology.",
                            ImageUrl = "https://images.unsplash.com/photo-1585792180666-f7347c490ee2?w=600&h=400&fit=crop",
                            IsActive = true,
                            IsFeatured = false,
                            Price = 9499.00m,
                            ProductName = "ASUS TUF Gaming 27\"",
                            SKU = "ASUS-TUF-VG279",
                            ShortDescription = "FHD 165Hz IPS Monitor",
                            StockQuantity = 30
                        },
                        new
                        {
                            ProductId = 8,
                            Brand = "Dell",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Dell S2722DGM 27-inch Curved Gaming Monitor with VA panel, QHD 2560x1440 resolution, 165Hz refresh rate, 2ms response time, FreeSync Premium. 1500R curvature for comfortable viewing.",
                            ImageUrl = "https://images.unsplash.com/photo-1551645120-d70bfe84c826?w=600&h=400&fit=crop",
                            IsActive = true,
                            IsFeatured = false,
                            Price = 11999.00m,
                            ProductName = "Dell S2722DGM 27\"",
                            SKU = "DELL-S2722DGM",
                            ShortDescription = "QHD 165Hz Curved VA",
                            StockQuantity = 20
                        },
                        new
                        {
                            ProductId = 9,
                            Brand = "G.Skill",
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "G.Skill Trident Z5 RGB 32GB DDR5 Memory Kit (2x16GB) running at 6000MHz with CL36 latency. Intel XMP 3.0 ready with stunning RGB lighting. Premium aluminum heatspreader.",
                            ImageUrl = "https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?w=600&h=400&fit=crop",
                            IsActive = true,
                            IsFeatured = true,
                            Price = 7499.00m,
                            ProductName = "G.Skill Trident Z5 RGB 32GB",
                            SKU = "GSKILL-Z5-32GB",
                            ShortDescription = "DDR5 6000MHz CL36 (2x16GB)",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 10,
                            Brand = "Corsair",
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Corsair Vengeance DDR5 32GB Memory Kit (2x16GB) running at 5600MHz with CL40 latency. Intel XMP 3.0 compatible with iCUE software support. Sleek aluminum heatspreader design.",
                            ImageUrl = "https://images.unsplash.com/photo-1562976540-1502c2145186?w=600&h=400&fit=crop",
                            IsActive = true,
                            IsFeatured = false,
                            Price = 5999.00m,
                            ProductName = "Corsair Vengeance DDR5 32GB",
                            SKU = "CORSAIR-VENG-32GB",
                            ShortDescription = "DDR5 5600MHz CL40 (2x16GB)",
                            StockQuantity = 35
                        },
                        new
                        {
                            ProductId = 11,
                            Brand = "Kingston",
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kingston Fury Beast 16GB DDR4 Memory Kit (2x8GB) running at 3200MHz with CL16 latency. Intel XMP ready, Plug N Play automatic overclocking. Low-profile heatspreader.",
                            ImageUrl = "https://images.unsplash.com/photo-1541140134513-85a161dc4a00?w=600&h=400&fit=crop",
                            IsActive = true,
                            IsFeatured = false,
                            Price = 2499.00m,
                            ProductName = "Kingston Fury Beast 16GB",
                            SKU = "KINGSTON-FURY-16GB",
                            ShortDescription = "DDR4 3200MHz CL16 (2x8GB)",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 12,
                            Brand = "TeamGroup",
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "TeamGroup T-Force Delta RGB 32GB DDR4 Memory Kit (2x16GB) running at 3600MHz with CL18 latency. Full-cover RGB lighting with 120° wide-angle design. Supports all major RGB software.",
                            ImageUrl = "https://images.unsplash.com/photo-1600861194942-f883de0dfe96?w=600&h=400&fit=crop",
                            IsActive = true,
                            IsFeatured = false,
                            Price = 3999.00m,
                            ProductName = "TeamGroup T-Force Delta RGB 32GB",
                            SKU = "TEAM-DELTA-32GB",
                            ShortDescription = "DDR4 3600MHz CL18 (2x16GB)",
                            StockQuantity = 30
                        },
                        new
                        {
                            ProductId = 13,
                            Brand = "Samsung",
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Samsung 990 Pro 2TB NVMe M.2 SSD with PCIe 4.0 interface, delivering up to 7450MB/s sequential read and 6900MB/s write speeds. Samsung V-NAND technology with intelligent thermal control.",
                            ImageUrl = "https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=600&h=400&fit=crop",
                            IsActive = true,
                            IsFeatured = true,
                            Price = 8999.00m,
                            ProductName = "Samsung 990 Pro 2TB",
                            SKU = "SAMSUNG-990PRO-2TB",
                            ShortDescription = "PCIe 4.0 NVMe M.2 7450MB/s",
                            StockQuantity = 25
                        },
                        new
                        {
                            ProductId = 14,
                            Brand = "Western Digital",
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "WD Black SN850X 1TB NVMe M.2 SSD with PCIe 4.0 interface, delivering up to 7300MB/s sequential read speeds. Game Mode 2.0 for predictive loading. Optional heatsink available.",
                            ImageUrl = "https://images.unsplash.com/photo-1531492746076-161ca9bcad58?w=600&h=400&fit=crop",
                            IsActive = true,
                            IsFeatured = true,
                            Price = 4999.00m,
                            ProductName = "WD Black SN850X 1TB",
                            SKU = "WD-SN850X-1TB",
                            ShortDescription = "PCIe 4.0 NVMe M.2 7300MB/s",
                            StockQuantity = 30
                        },
                        new
                        {
                            ProductId = 15,
                            Brand = "Crucial",
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Crucial P3 Plus 1TB NVMe M.2 SSD with PCIe 4.0 interface, delivering up to 5000MB/s sequential read speeds. Great value for everyday computing and gaming. Micron Advanced 3D NAND.",
                            ImageUrl = "https://images.unsplash.com/photo-1628557044797-f21d1d65f9e4?w=600&h=400&fit=crop",
                            IsActive = true,
                            IsFeatured = false,
                            Price = 2999.00m,
                            ProductName = "Crucial P3 Plus 1TB",
                            SKU = "CRUCIAL-P3PLUS-1TB",
                            ShortDescription = "PCIe 4.0 NVMe M.2 5000MB/s",
                            StockQuantity = 45
                        },
                        new
                        {
                            ProductId = 16,
                            Brand = "Kingston",
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kingston NV2 500GB NVMe M.2 SSD with PCIe 4.0 interface, delivering up to 3500MB/s sequential read speeds. Compact M.2 2280 form factor. Low power consumption for cooler operation.",
                            ImageUrl = "https://images.unsplash.com/photo-1647503380147-dd2cf8fc3ac9?w=600&h=400&fit=crop",
                            IsActive = true,
                            IsFeatured = false,
                            Price = 1499.00m,
                            ProductName = "Kingston NV2 500GB",
                            SKU = "KINGSTON-NV2-500GB",
                            ShortDescription = "PCIe 4.0 NVMe M.2 3500MB/s",
                            StockQuantity = 60
                        },
                        new
                        {
                            ProductId = 17,
                            Brand = "Logitech",
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Logitech G Pro X Superlight 2 Wireless Gaming Mouse weighing only 60g. HERO 2 sensor with 32K DPI, LIGHTSPEED wireless, 95+ hour battery life. Esports-grade performance in an ultra-lightweight design.",
                            ImageUrl = "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600&h=400&fit=crop",
                            IsActive = true,
                            IsFeatured = true,
                            Price = 6499.00m,
                            ProductName = "Logitech G Pro X Superlight 2",
                            SKU = "LOGI-GPXSL2",
                            ShortDescription = "Wireless Gaming Mouse 60g",
                            StockQuantity = 25
                        },
                        new
                        {
                            ProductId = 18,
                            Brand = "Razer",
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Razer DeathAdder V3 Pro Wireless Gaming Mouse with iconic ergonomic shape. Focus Pro 30K sensor, HyperSpeed wireless, 90 hour battery. Ultra-lightweight at only 63g for competitive gaming.",
                            ImageUrl = "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=600&h=400&fit=crop",
                            IsActive = true,
                            IsFeatured = true,
                            Price = 5999.00m,
                            ProductName = "Razer DeathAdder V3 Pro",
                            SKU = "RAZER-DAV3PRO",
                            ShortDescription = "Wireless Ergonomic Mouse 63g",
                            StockQuantity = 20
                        },
                        new
                        {
                            ProductId = 19,
                            Brand = "SteelSeries",
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "SteelSeries Aerox 3 Wireless Gaming Mouse with honeycomb shell design at 66g. TrueMove Air sensor, 200+ hour battery life, water resistant IP54 rating. AquaBarrier protection included.",
                            ImageUrl = "https://images.unsplash.com/photo-1613141411244-0e4ac259d217?w=600&h=400&fit=crop",
                            IsActive = true,
                            IsFeatured = false,
                            Price = 3499.00m,
                            ProductName = "SteelSeries Aerox 3 Wireless",
                            SKU = "SS-AEROX3-WL",
                            ShortDescription = "Ultra-Lightweight Gaming Mouse 66g",
                            StockQuantity = 35
                        },
                        new
                        {
                            ProductId = 20,
                            Brand = "HyperX",
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "HyperX Pulsefire Haste 2 Ultra-Lightweight Wired Gaming Mouse at just 53g. 26K sensor, 8000Hz polling rate, 100 hour battery (wireless version). Flexible paracord cable included.",
                            ImageUrl = "https://images.unsplash.com/photo-1623126908029-58cb08a2b272?w=600&h=400&fit=crop",
                            IsActive = true,
                            IsFeatured = false,
                            Price = 2199.00m,
                            ProductName = "HyperX Pulsefire Haste 2",
                            SKU = "HX-HASTE2",
                            ShortDescription = "Wired Gaming Mouse 53g",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 21,
                            Brand = "Corsair",
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Corsair K100 RGB Optical-Mechanical Gaming Keyboard with OPX switches. iCUE control wheel, PBT double-shot keycaps, 44-zone LightEdge RGB, magnetic wrist rest. Ultimate flagship keyboard.",
                            ImageUrl = "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&h=400&fit=crop",
                            IsActive = true,
                            IsFeatured = true,
                            Price = 8999.00m,
                            ProductName = "Corsair K100 RGB",
                            SKU = "CORSAIR-K100",
                            ShortDescription = "Optical-Mechanical Full-Size",
                            StockQuantity = 15
                        },
                        new
                        {
                            ProductId = 22,
                            Brand = "Razer",
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Razer Huntsman V3 Pro TKL Gaming Keyboard with analog optical switches. Adjustable actuation, magnetic wrist rest, PBT keycaps, multi-function digital dial. Per-key RGB with Razer Chroma.",
                            ImageUrl = "https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=600&h=400&fit=crop",
                            IsActive = true,
                            IsFeatured = true,
                            Price = 7499.00m,
                            ProductName = "Razer Huntsman V3 Pro TKL",
                            SKU = "RAZER-HUNTSV3-TKL",
                            ShortDescription = "Analog Optical TKL Keyboard",
                            StockQuantity = 18
                        },
                        new
                        {
                            ProductId = 23,
                            Brand = "Logitech",
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Logitech G915 TKL LIGHTSPEED Wireless Gaming Keyboard with low-profile GL switches. LIGHTSPEED wireless, Bluetooth, 40 hour battery, aircraft-grade aluminum. Premium slim design.",
                            ImageUrl = "https://images.unsplash.com/photo-1595225476474-87563907a212?w=600&h=400&fit=crop",
                            IsActive = true,
                            IsFeatured = false,
                            Price = 5999.00m,
                            ProductName = "Logitech G915 TKL Lightspeed",
                            SKU = "LOGI-G915TKL",
                            ShortDescription = "Wireless Low-Profile TKL",
                            StockQuantity = 22
                        },
                        new
                        {
                            ProductId = 24,
                            Brand = "HyperX",
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "HyperX Alloy Origins 65 Compact Mechanical Keyboard with HyperX Red linear switches. Aircraft-grade aluminum body, PBT keycaps, per-key RGB lighting. 65% layout with arrow keys retained.",
                            ImageUrl = "https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?w=600&h=400&fit=crop",
                            IsActive = true,
                            IsFeatured = false,
                            Price = 2999.00m,
                            ProductName = "HyperX Alloy Origins 65",
                            SKU = "HX-ORIGINS65",
                            ShortDescription = "Compact Mechanical 65%",
                            StockQuantity = 30
                        },
                        new
                        {
                            ProductId = 25,
                            Brand = "AMD",
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "AMD Ryzen 9 7950X3D 16-Core 32-Thread Desktop Processor with 3D V-Cache technology. 5.7GHz max boost, 128MB L3 cache, AM5 socket. The ultimate gaming and productivity processor.",
                            ImageUrl = "https://images.unsplash.com/photo-1591799265444-d66432b91588?w=600&h=400&fit=crop",
                            IsActive = true,
                            IsFeatured = true,
                            Price = 27999.00m,
                            ProductName = "AMD Ryzen 9 7950X3D",
                            SKU = "AMD-7950X3D",
                            ShortDescription = "16-Core 3D V-Cache Gaming CPU",
                            StockQuantity = 10
                        },
                        new
                        {
                            ProductId = 26,
                            Brand = "Intel",
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Intel Core i9-14900K 24-Core (8P+16E) Desktop Processor. 6.0GHz max turbo, 36MB cache, LGA1700 socket. Unlocked for overclocking with Intel Thermal Velocity Boost.",
                            ImageUrl = "https://images.unsplash.com/photo-1555617981-dac3880eac6e?w=600&h=400&fit=crop",
                            IsActive = true,
                            IsFeatured = true,
                            Price = 25999.00m,
                            ProductName = "Intel Core i9-14900K",
                            SKU = "INTEL-I9-14900K",
                            ShortDescription = "24-Core Flagship Desktop CPU",
                            StockQuantity = 12
                        },
                        new
                        {
                            ProductId = 27,
                            Brand = "AMD",
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "AMD Ryzen 7 7800X3D 8-Core 16-Thread Desktop Processor with 3D V-Cache. 5.0GHz max boost, 96MB L3 cache, AM5 socket. Best value gaming processor with incredible performance.",
                            ImageUrl = "https://images.unsplash.com/photo-1592664474496-8f2c35acd655?w=600&h=400&fit=crop",
                            IsActive = true,
                            IsFeatured = true,
                            Price = 17499.00m,
                            ProductName = "AMD Ryzen 7 7800X3D",
                            SKU = "AMD-7800X3D",
                            ShortDescription = "8-Core 3D V-Cache Gaming CPU",
                            StockQuantity = 20
                        },
                        new
                        {
                            ProductId = 28,
                            Brand = "Intel",
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Intel Core i5-14600K 14-Core (6P+8E) Desktop Processor. 5.3GHz max turbo, 24MB cache, LGA1700 socket. Unlocked for overclocking, excellent gaming and multitasking performance.",
                            ImageUrl = "https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&h=400&fit=crop",
                            IsActive = true,
                            IsFeatured = false,
                            Price = 12999.00m,
                            ProductName = "Intel Core i5-14600K",
                            SKU = "INTEL-I5-14600K",
                            ShortDescription = "14-Core Mid-Range Desktop CPU",
                            StockQuantity = 25
                        },
                        new
                        {
                            ProductId = 29,
                            Brand = "NVIDIA",
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "NVIDIA GeForce RTX 4090 Founders Edition with 24GB GDDR6X memory. Ada Lovelace architecture, DLSS 3, 2520MHz boost clock. The most powerful consumer graphics card for 4K gaming and AI workloads.",
                            ImageUrl = "https://images.unsplash.com/photo-1591488320449-011701bb6704?w=600&h=400&fit=crop",
                            IsActive = true,
                            IsFeatured = true,
                            Price = 89999.00m,
                            ProductName = "NVIDIA RTX 4090 Founders Edition",
                            SKU = "NVIDIA-RTX4090-FE",
                            ShortDescription = "24GB GDDR6X Flagship GPU",
                            StockQuantity = 5
                        },
                        new
                        {
                            ProductId = 30,
                            Brand = "ASUS",
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "ASUS ROG Strix GeForce RTX 4080 SUPER with 16GB GDDR6X memory. Axial-tech fans, 3.15 slot design, 2640MHz boost clock. Premium cooling and RGB lighting for enthusiast builds.",
                            ImageUrl = "https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=600&h=400&fit=crop",
                            IsActive = true,
                            IsFeatured = true,
                            Price = 54999.00m,
                            ProductName = "ASUS ROG Strix RTX 4080 SUPER",
                            SKU = "ASUS-RTX4080S-STRIX",
                            ShortDescription = "16GB GDDR6X Premium GPU",
                            StockQuantity = 8
                        },
                        new
                        {
                            ProductId = 31,
                            Brand = "MSI",
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "MSI Gaming X Trio GeForce RTX 4070 Ti SUPER with 16GB GDDR6X memory. TRI FROZR 3 cooling, 2640MHz boost clock. Excellent 1440p and 4K gaming performance.",
                            ImageUrl = "https://images.unsplash.com/photo-1555618254-5e06a5e9d678?w=600&h=400&fit=crop",
                            IsActive = true,
                            IsFeatured = false,
                            Price = 42999.00m,
                            ProductName = "MSI Gaming X Trio RTX 4070 Ti SUPER",
                            SKU = "MSI-RTX4070TIS-GXT",
                            ShortDescription = "16GB GDDR6X High-End GPU",
                            StockQuantity = 12
                        },
                        new
                        {
                            ProductId = 32,
                            Brand = "Gigabyte",
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Gigabyte GeForce RTX 4060 Eagle OC with 8GB GDDR6 memory. WINDFORCE cooling, 2475MHz boost clock, ultra-durable components. Perfect for 1080p high-refresh gaming.",
                            ImageUrl = "https://images.unsplash.com/photo-1622219809260-ce065fc5277f?w=600&h=400&fit=crop",
                            IsActive = true,
                            IsFeatured = false,
                            Price = 14999.00m,
                            ProductName = "Gigabyte RTX 4060 Eagle OC",
                            SKU = "GIGA-RTX4060-EAGLE",
                            ShortDescription = "8GB GDDR6 Mainstream GPU",
                            StockQuantity = 30
                        });
                });

            modelBuilder.Entity("Arcade.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@arcade.com",
                            FailedLoginAttempts = 0,
                            FullName = "Admin User",
                            IsActive = true,
                            PasswordHash = "$2a$11$Uw2NSbcyTC8wom1YEchTPuV.eTyITOscaKNikN9E54zf1HUZfI/qC",
                            Role = "Admin"
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john@arcade.com",
                            FailedLoginAttempts = 0,
                            FullName = "John Doe",
                            IsActive = true,
                            PasswordHash = "$2a$11$0vTyhMfGAY56h1v.gGbzHu8EtAh4usIUivBDlZCsPMLA6dmyBoUG6",
                            Role = "Customer"
                        });
                });

            modelBuilder.Entity("Arcade.Models.CartItem", b =>
                {
                    b.HasOne("Arcade.Models.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Arcade.Models.User", "User")
                        .WithMany("CartItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Arcade.Models.Order", b =>
                {
                    b.HasOne("Arcade.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Arcade.Models.OrderDetail", b =>
                {
                    b.HasOne("Arcade.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Arcade.Models.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Arcade.Models.Product", b =>
                {
                    b.HasOne("Arcade.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Arcade.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Arcade.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("Arcade.Models.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("Arcade.Models.User", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
